/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.pessoa.Cliente;
import model.pessoa.Corretor;
import model.Imovel;


/**
 *
 * @author alunocomp
 */
public class PrincipalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrincipalJPanel
     */
    Controller controller;
    DefaultListModel Cliente_List = new DefaultListModel();
    DefaultListModel Corretor_List = new DefaultListModel();
    DefaultListModel Imovel_List = new DefaultListModel();

    public PrincipalJPanel(Controller controller) {
        this.controller = controller;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        c_cliente_nome = new javax.swing.JTextField();
        c_cliente_end = new javax.swing.JTextField();
        c_cliente_tel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        c_cliente_email = new javax.swing.JTextField();
        btn_cliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        c_cliente_lista = new javax.swing.JList(controller.getClientes().toArray());
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        c_corretor_nome = new javax.swing.JTextField();
        c_corretor_end = new javax.swing.JTextField();
        c_corretor_tel = new javax.swing.JTextField();
        c_corretor_com = new javax.swing.JTextField();
        btn_corretor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        c_corretor_lista = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        c_imovel_cod = new javax.swing.JTextField();
        c_imovel_vend = new javax.swing.JTextField();
        c_imovel_end = new javax.swing.JTextField();
        c_imovel_quartos = new javax.swing.JTextField();
        c_imovel_tipo = new javax.swing.JTextField();
        c_imovel_valor = new javax.swing.JTextField();
        btn_imovel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        c_imovel_lista = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        c_visita_imovel = new javax.swing.JTextField();
        c_visita_data = new javax.swing.JTextField();
        c_visita_gasto = new javax.swing.JTextField();
        c_visita_cliente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        c_visita_corretor = new javax.swing.JTextField();
        btn_visita = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        c_visita_lista = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        c_venda_imovel = new javax.swing.JTextField();
        c_venda_cliente = new javax.swing.JTextField();
        c_venda_valor = new javax.swing.JTextField();
        c_venda_corretor = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        c_venda_lista = new javax.swing.JList<>();
        btn_venda = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        c_relatorio_mes = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        c_relatorio_lista = new javax.swing.JList<>();
        btn_mensal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        c_relatorio_ano = new javax.swing.JTextField();
        btn_anual = new javax.swing.JButton();

        jTabbedPane1.setBackground(new java.awt.Color(252, 252, 252));

        c_cliente_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cliente_nomeActionPerformed(evt);
            }
        });

        c_cliente_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cliente_endActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Endereço:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Email:");

        btn_cliente.setText("Cadastrar");
        btn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clienteActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(c_cliente_lista);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c_cliente_nome)
                    .addComponent(c_cliente_end)
                    .addComponent(c_cliente_tel)
                    .addComponent(c_cliente_email))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btn_cliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_cliente_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_cliente_end, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_cliente_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_cliente_email, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btn_cliente)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        jLabel7.setText("Nome:");

        jLabel8.setText("Endereço:");

        jLabel9.setText("Telefone:");

        jLabel10.setText("Comissão:");

        c_corretor_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_corretor_nomeActionPerformed(evt);
            }
        });

        c_corretor_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_corretor_endActionPerformed(evt);
            }
        });

        c_corretor_com.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btn_corretor.setText("Cadastrar");
        btn_corretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_corretorActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(c_corretor_lista);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_corretor_com)
                            .addComponent(c_corretor_tel)
                            .addComponent(c_corretor_end)
                            .addComponent(c_corretor_nome)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_corretor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_corretor_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_corretor_end, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_corretor_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_corretor_com, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addComponent(btn_corretor)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Corretor", jPanel2);

        jLabel12.setText("Código:");

        jLabel13.setText("Email Vendedor:");

        jLabel14.setText("Endereço:");

        jLabel15.setText("Quartos:");

        jLabel16.setText("Tipo:");

        jLabel17.setText("Valor:");

        btn_imovel.setText("Cadastrar");
        btn_imovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imovelActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(c_imovel_lista);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c_imovel_cod)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_imovel_quartos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(c_imovel_end, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(c_imovel_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel16)
                                                .addGap(10, 10, 10)
                                                .addComponent(c_imovel_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(btn_imovel))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c_imovel_vend)))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_imovel_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_imovel_quartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(c_imovel_vend, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_imovel_end, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_imovel_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(c_imovel_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(btn_imovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Imóvel", jPanel3);

        jLabel19.setText("Cód. Imóvel:");

        jLabel20.setText("Data:");

        jLabel21.setText("Gasto:");

        jLabel22.setText("Cliente:");

        jLabel23.setText("Corretor:");

        btn_visita.setText("Agendar");

        jScrollPane4.setViewportView(c_visita_lista);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btn_visita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_visita_data, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_visita_imovel)
                    .addComponent(c_visita_gasto)
                    .addComponent(c_visita_cliente)
                    .addComponent(c_visita_corretor))
                .addGap(19, 19, 19))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(c_visita_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(c_visita_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(c_visita_gasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(c_visita_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(c_visita_corretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_visita)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Visita", jPanel4);

        jLabel24.setText("Cód. Imóvel:");

        jLabel25.setText("Cliente:");

        jLabel26.setText("Valor:");

        jLabel27.setText("Corretor:");

        jScrollPane5.setViewportView(c_venda_lista);

        btn_venda.setText("Vender");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(c_venda_valor)
                            .addComponent(c_venda_cliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(c_venda_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(c_venda_corretor))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btn_venda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(c_venda_imovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(c_venda_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(c_venda_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(c_venda_corretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_venda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Venda", jPanel5);

        jLabel1.setText("Mês:");

        jScrollPane6.setViewportView(c_relatorio_lista);

        btn_mensal.setText("Gerar Mensal");

        jLabel6.setText("Ano:");

        btn_anual.setText("Gerar Anual");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(c_relatorio_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_mensal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c_relatorio_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_anual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(c_relatorio_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(c_relatorio_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mensal)
                    .addComponent(btn_anual))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Finanças", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void c_cliente_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cliente_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cliente_nomeActionPerformed

    private void c_cliente_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cliente_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cliente_endActionPerformed

    void updateListClientes() {
        Cliente_List.removeAllElements();
        for (int i = 0; i < controller.getClientes().size(); i++) {
            Cliente_List.addElement(controller.getClientes().get(i));
            System.out.print(controller.getClientes().get(i));
        }
        c_cliente_lista.setModel(Cliente_List);
    }
    
    void updateListCorretor() {
        Corretor_List.removeAllElements();
        for (int i = 0; i < controller.getCorretor().size(); i++) {
            Corretor_List.addElement(controller.getCorretor().get(i));
            System.out.print(controller.getCorretor().get(i));
        }
        c_corretor_lista.setModel(Corretor_List);
    }
    
    void updateListImovel() {
        Imovel_List.removeAllElements();
        for (int i = 0; i < controller.getImoveis().size(); i++) {
            Imovel_List.addElement(controller.getImoveis().get(i));
            System.out.print(controller.getImoveis().get(i));
        }
        c_imovel_lista.setModel(Imovel_List);
    }
    

    private void btn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clienteActionPerformed
// TODO add your handling code here:
        if (controller.temNumero(c_cliente_nome.getText())) {
            JOptionPane.showMessageDialog(null, "Nome não pode conter números!");
        } else if (c_cliente_nome.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Nome curto demais!");
        } else if (controller.temLetra(c_cliente_tel.getText())) {
            JOptionPane.showMessageDialog(null, "Telefone não pode conter letras!");
        } else if (c_cliente_tel.getText().length() < 7) {
            JOptionPane.showMessageDialog(null, "Telefone deve conter no minimo 8 números!");
        } else if (c_cliente_end.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Endereço curto demais!");
        } else if (controller.temArroba(c_cliente_email.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Email deve conter @!");
        } else if (c_cliente_email.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Email curto demais!");
        } else {
            Cliente newCliente = new Cliente(c_cliente_nome.getText(),
                    c_cliente_end.getText(),
                    c_cliente_tel.getText(),
                    c_cliente_email.getText()
            );
            if (controller.findCliente(c_cliente_email.getText()) != null) {
                JOptionPane.showMessageDialog(null, "Cliente já existe!");
            } else {
                controller.addClientes(newCliente);
                c_cliente_nome.setText("");
                c_cliente_end.setText("");
                c_cliente_tel.setText("");
                c_cliente_email.setText("");
                updateListClientes();
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            }

        }
    }//GEN-LAST:event_btn_clienteActionPerformed

    private void c_corretor_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_corretor_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_corretor_nomeActionPerformed

    private void c_corretor_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_corretor_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_corretor_endActionPerformed

    private void btn_corretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_corretorActionPerformed
        // TODO add your handling code here:
        if (controller.temNumero(c_corretor_nome.getText())) {
            JOptionPane.showMessageDialog(null, "Nome não pode conter números!");
        } else if (c_corretor_nome.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Nome curto demais!");
        } else if (controller.temLetra(c_corretor_tel.getText())) {
            JOptionPane.showMessageDialog(null, "Telefone não pode conter letras!");
        } else if (c_corretor_tel.getText().length() < 7) {
            JOptionPane.showMessageDialog(null, "Telefone deve conter no minimo 8 números!");
        } else if (c_corretor_end.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Endereço curto demais!");
        } else if (controller.temLetra(c_corretor_com.getText())) {
            JOptionPane.showMessageDialog(null, "Comissao só deve conter numeros!");
        } else {
            float f = Float.valueOf(c_corretor_com.getText());
            Corretor newCorretor = new Corretor(f,
                    c_corretor_nome.getText(),
                    c_corretor_end.getText(),
                    c_corretor_tel.getText()
            );
            if (controller.findCorretor(newCorretor) != null) {
                JOptionPane.showMessageDialog(null, "Corretor já existe!");
            } else {
                controller.addCorretor(newCorretor);
                c_corretor_nome.setText("");
                c_corretor_end.setText("");
                c_corretor_tel.setText("");
                c_corretor_com.setText("");
                updateListCorretor();
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            }

        }
    }//GEN-LAST:event_btn_corretorActionPerformed

    private void btn_imovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imovelActionPerformed
        // TODO add your handling code here:
        if (controller.temLetra(c_imovel_cod.getText())) {
            JOptionPane.showMessageDialog(null, "Código não pode conter letras!");
        } else if (c_imovel_cod.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Código curto demais!");
        } else if (controller.temNumero(c_imovel_vend.getText())) {
            JOptionPane.showMessageDialog(null, "Vendedor não pode conter números!");
        } else if (c_imovel_vend.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Vendedor curto demais!");
        } else if (c_imovel_end.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Endereço curto demais!");
        } else if (controller.temLetra(c_imovel_tipo.getText())) {
            JOptionPane.showMessageDialog(null, "Tipo só pode conter números!");
        } else if (c_imovel_tipo.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Tipo curto demais!");
        } else if (controller.temLetra(c_imovel_quartos.getText())) {
            JOptionPane.showMessageDialog(null, "Quartos só pode conter números!");
        } else if (c_imovel_quartos.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Quartos curto demais!");
        } else if (controller.temLetra(c_imovel_valor.getText())) {
            JOptionPane.showMessageDialog(null, "Valor só pode conter números!");
        } else if (c_imovel_valor.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Valor curto demais!");
        } else if (controller.findCliente(c_imovel_vend.getText()) == null) {
            JOptionPane.showMessageDialog(null, "Vendedor inválido!");
        } else {
            int cod = Integer.parseInt(c_imovel_cod.getText());
            int tipo = Integer.parseInt(c_imovel_tipo.getText());
            int quartos = Integer.parseInt(c_imovel_quartos.getText());
            float valor = Float.valueOf(c_imovel_valor.getText());

            Imovel newImovel = new Imovel(cod,
                    controller.findCliente(c_imovel_vend.getText()),
                    c_imovel_end.getText(),
                    tipo,
                    quartos,
                    valor
            );
            if (controller.findImovel(newImovel) != null) {
                JOptionPane.showMessageDialog(null, "Imovel já existe!");
            } else {
                controller.addImovel(newImovel);
                c_imovel_cod.setText("");
                c_imovel_vend.setText("");
                c_imovel_end.setText("");
                c_imovel_tipo.setText("");
                c_imovel_quartos.setText("");
                c_imovel_valor.setText("");
                updateListImovel();
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            }
        }
    }//GEN-LAST:event_btn_imovelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anual;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_corretor;
    private javax.swing.JButton btn_imovel;
    private javax.swing.JButton btn_mensal;
    private javax.swing.JButton btn_venda;
    private javax.swing.JButton btn_visita;
    private javax.swing.JTextField c_cliente_email;
    private javax.swing.JTextField c_cliente_end;
    private javax.swing.JList<String> c_cliente_lista;
    private javax.swing.JTextField c_cliente_nome;
    private javax.swing.JTextField c_cliente_tel;
    private javax.swing.JTextField c_corretor_com;
    private javax.swing.JTextField c_corretor_end;
    private javax.swing.JList<String> c_corretor_lista;
    private javax.swing.JTextField c_corretor_nome;
    private javax.swing.JTextField c_corretor_tel;
    private javax.swing.JTextField c_imovel_cod;
    private javax.swing.JTextField c_imovel_end;
    private javax.swing.JList<String> c_imovel_lista;
    private javax.swing.JTextField c_imovel_quartos;
    private javax.swing.JTextField c_imovel_tipo;
    private javax.swing.JTextField c_imovel_valor;
    private javax.swing.JTextField c_imovel_vend;
    private javax.swing.JTextField c_relatorio_ano;
    private javax.swing.JList<String> c_relatorio_lista;
    private javax.swing.JTextField c_relatorio_mes;
    private javax.swing.JTextField c_venda_cliente;
    private javax.swing.JTextField c_venda_corretor;
    private javax.swing.JTextField c_venda_imovel;
    private javax.swing.JList<String> c_venda_lista;
    private javax.swing.JTextField c_venda_valor;
    private javax.swing.JTextField c_visita_cliente;
    private javax.swing.JTextField c_visita_corretor;
    private javax.swing.JTextField c_visita_data;
    private javax.swing.JTextField c_visita_gasto;
    private javax.swing.JTextField c_visita_imovel;
    private javax.swing.JList<String> c_visita_lista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
